### ISSUE TITLE
TypeError: _AlternatingHighwayLSTMFunction.forward: `ctx` is not present

### ISSUE THREAD

**Issue by zacharyWongZ** [KaihuaTang/VCTree-Scene-Graph-Generation#7]
when i run "bash ./scripts/train_vctreenet.sh  5",and go error is : 
hoping your help,thanks.
Traceback (most recent call last):
  File "models/train_rels.py", line 24, in <module>
    from lib.rel_model import RelModel
  File "/home/wang/VCTree-Scene-Graph-Generation/lib/rel_model.py", line 31, in <module>
    from lib.tree_lstm import tree_lstm, gen_tree, tree_utils
  File "/home/wang/VCTree-Scene-Graph-Generation/lib/tree_lstm/tree_lstm.py", line 8, in <module>
    from lib.lstm.highway_lstm_cuda.alternating_highway_lstm import block_orthogonal
  File "/home/wang/VCTree-Scene-Graph-Generation/lib/lstm/highway_lstm_cuda/alternating_highway_lstm.py", line 62, in <module>
    class _AlternatingHighwayLSTMFunction(Function):
  File "/home/wang/VCTree-Scene-Graph-Generation/lib/lstm/highway_lstm_cuda/alternating_highway_lstm.py", line 79, in _AlternatingHighwayLSTMFunction
    gates: torch.Tensor)-> Tuple[torch.Tensor, None]:
  File "/home/wang/anaconda3/envs/VCTree/lib/python3.6/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/wang/anaconda3/envs/VCTree/lib/python3.6/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/wang/anaconda3/envs/VCTree/lib/python3.6/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/wang/anaconda3/envs/VCTree/lib/python3.6/site-packages/overrides/signature.py", line 95, in ensure_signature_is_compatible
    super_sig, sub_sig, super_type_hints, sub_type_hints, is_static, method_name
  File "/home/wang/anaconda3/envs/VCTree/lib/python3.6/site-packages/overrides/signature.py", line 137, in ensure_all_kwargs_defined_in_sub
    raise TypeError(f"{method_name}: `{name}` is not present.")
TypeError: _AlternatingHighwayLSTMFunction.forward: `ctx` is not present

**Comment by moshuilanting** [comment]
I also encountered the same problem, which can be solved by installing the old version of overrides
pip install overrides==1.9
